### ISSUE TITLE
Empty filltypes 

### ISSUE THREAD

**Issue by Michaelj15** [Achimobil/FS22_BigDisplay#16]
Is it possible to display empty filltypes? On the moment empty lines will not be displayed.

**Comment by Achimobil** [comment]
currently not because 99% of the users do not want to trash the display full with information they don't need.
Imagine on a map with 200 filltypes you have 200 items on the list at a pallet storage and only one is filled.

But I put it on the wishlist. When the Displays get synced inline settings this will be one of the possibilites

**Comment by Michaelj15** [comment]
> currently not because 99% of the users do not want to trash the display full with information they don't need. Imagine on a map with 200 filltypes you have 200 items on the list at a pallet storage and only one is filled.
> 
> But I put it on the wishlist. When the Displays get synced inline settings this will be one of the possibilites

No problem and thank you! It's indeed messy with a lot of filltypes.

**Comment by Achimobil** [comment]
Im 22er gibt es keine Features mehr. Deshalb close ich das hier
