### ISSUE TITLE
Display not working with chicken pens and sheep pastures.

### ISSUE THREAD

**Issue by Inerti** [Achimobil/FS22_BigDisplay#20]
Chicken pens and sheep pastures not showing food amount on display. Works ok with cows, horses and pigs.

**Comment by Achimobil** [comment]
The reason is found:
They do not have any storage for the LS.

Only when they have a storage with a unloading or loading station a animal pen can be shown.
So when buillding the sheep pen which needs water, there is a storage registered and I can get the data.
Also when there is any other storage in like liquid manure there is a storage registered.

So technically I could not do anything against this, but I will update the description for the next update that it works only for pens with storage
