### ISSUE TITLE
"Fehler beim beenden des Spiels gehoben", – on the contrary, I got an error.

### ISSUE THREAD

**Issue by vitalii2011** [Achimobil/FS22_BigDisplay#23]
When exiting, the game freezes and shows a place with traces of distant production facilities and pens:
![fsScreen_2024_02_03_18_09_53](https://github.com/Achimobil/FS22_BigDisplay/assets/41552153/bb0cf4ce-cc35-4e27-9be8-48ad8494e205)
Error: Running LUA method 'mouseEvent'.
`C:/Users/…/Documents/My Games/FarmingSimulator2022/mods/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua:29: attempt to concatenate global 'g_currentModName' (a nil value)`

**Comment by johnwayne1930** [comment]
Same here, since 1.0.0.1. On game exit it freeze in an akward camera angle.

2024-02-03 12:08 Error: Running LUA method 'mouseEvent'.
C:/Users/xxx/Documents/My Games/FarmingSimulator2022/mods/FS22_BigDisplay/scripts/bigDisplaySpecialization.lua:29: attempt to concatenate global 'g_currentModName' (a nil value)
[log_BigDisplay.txt](https://github.com/Achimobil/FS22_BigDisplay/files/14152209/log_BigDisplay.txt)

**Comment by Achimobil** [comment]
Duplikate, gehört zu #22

**Comment by vitalii2011** [comment]
In 1.0.0.2 this problem no longer exists. Thank you.
